name: Build AnnData h5ad

on:
  workflow_dispatch:   # 手动触发
  schedule:
    - cron: '0 0 * * 0' # 每周日自动运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade spatialdata squidpy

      - name: Run script to build h5ad
        run: python get_spatial_data.py

      - name: Upload h5ad artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest_h5ad
          path: pbmc_small.h5ad

